name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew :app:bundleRelease
      
    - name: List output files
      run: find app/build/outputs -type f
      
    - name: Create output directory
      run: mkdir -p output
      
    - name: Copy AAB file
      run: cp app/build/outputs/bundle/release/app-release.aab output/ || echo "AAB file not found"
      
    - name: Upload output directory
      uses: actions/upload-artifact@v3
      with:
        name: app-outputs
        path: output 
